"""fix Doc models_2

Revision ID: df5bdf07c817
Revises: 122c2bbfc7c1
Create Date: 2026-02-08 15:43:18.219988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df5bdf07c817'
down_revision: Union[str, Sequence[str], None] = '122c2bbfc7c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_docs', 'filename')
    op.drop_column('price_docs', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_docs', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('price_docs', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
